
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.DataClasses.Alarm.Parse(System.String)~System.Collections.Generic.IList{SonosUPnP.DataClasses.Alarm}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.DataClasses.AvailableServices.ParseServiceDescriptionList(System.String)~System.Collections.Generic.List{SonosUPnP.DataClasses.AvailableService}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.DataClasses.ZoneGroupStateList.ParseZoneGroupStates(System.String)~System.Collections.Generic.List{SonosUPnP.DataClasses.ZoneGroup}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.SonosItem.Parse(System.String)~System.Collections.Generic.List{SonosUPnP.SonosItem}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.SonosItem.ParseSingleItem(System.String)~SonosUPnP.SonosItem")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Codequalität", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:SonosUPnP.SonosPlayer.ServiceCheckTimer")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.AVTransport.RemoveTrackRangeFromQueue(System.UInt16,System.UInt16,System.UInt16)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.Queue.CreateQueue(System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaServerServices.ContentDirectory.FindPrefix(System.String,System.String)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.DeviceProperties.GetAutoplayLinkedZones(System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.DeviceProperties.GetAutoplayVolume(System.String)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaServerServices.ContentDirectory.GetBrowseable~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.RenderingControl.GetEQ(System.String,System.UInt32)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Props.ZoneMethods.AddToQueue(System.String,SonosUPnP.SonosPlayer)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaServerServices.ContentDirectory.GetLastIndexChange~System.Threading.Tasks.Task{System.DateTime}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.SystemProperties.GetRDM~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.RenderingControl.GetSupportsOutputFixed(System.UInt32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaServerServices.ContentDirectory.GetSystemUpdateID~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.AlarmClock.GetTimeNow(System.Int32)~System.Threading.Tasks.Task{SonosUPnP.DataClasses.CurrentTime}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.DeviceProperties.GetUseAutoplayVolume(System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.RenderingControl.GetVolumeDB(SonosUPnP.DataClasses.SonosEnums.SpeakerSelection,System.UInt32)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.RenderingControl.RampToVolume(System.String,System.Boolean,System.UInt16,SonosUPnP.DataClasses.SonosEnums.RampTypes,SonosUPnP.DataClasses.SonosEnums.SpeakerSelection,System.UInt32)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.Queue.RemoveAllTracks(System.UInt16,System.UInt16)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.Queue.RemoveTrackRange(System.UInt16,System.UInt16,System.UInt16,System.UInt16)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.Queue.ReorderTracks(System.UInt16,System.UInt16,System.UInt16,System.UInt16,System.UInt16)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.GroupRenderingControl.SetRelativeGroupVolume(System.UInt16,System.UInt32)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.RenderingControl.SetRelativeVolume(System.UInt16,SonosUPnP.DataClasses.SonosEnums.SpeakerSelection,System.UInt32)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Performance", "CA1806:Methodenergebnisse nicht ignorieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Services.MediaRendererService.RenderingControl.SetVolume(System.Int32,SonosUPnP.DataClasses.SonosEnums.SpeakerSelection,System.UInt32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1822:Member als statisch markieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:SonosUPnP.Props.ZoneMethods.CreateFavorite(SonosUPnP.SonosPlayer,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1822:Member als statisch markieren", Justification = "<Ausstehend>", Scope = "member", Target = "~P:SonosUPnP.Props.DiscoveryZoneProperties.ListOfAlarms")]
[assembly: SuppressMessage("Performance", "CA1822:Member als statisch markieren", Justification = "<Ausstehend>", Scope = "member", Target = "~P:SonosUPnP.Props.DiscoveryZoneProperties.ListOfFavorites")]
[assembly: SuppressMessage("Performance", "CA1822:Member als statisch markieren", Justification = "<Ausstehend>", Scope = "member", Target = "~P:SonosUPnP.Props.DiscoveryZoneProperties.ListOfImportedPlaylist")]
[assembly: SuppressMessage("Performance", "CA1822:Member als statisch markieren", Justification = "<Ausstehend>", Scope = "member", Target = "~P:SonosUPnP.Props.DiscoveryZoneProperties.ListOfSonosPlaylist")]
